# Base image
FROM golang:1.14-alpine

# Specify work diectory
WORKDIR /go/src/app/

# Modules file allocation settings
COPY src/app/go.mod ./
COPY src/app/go.sum ./

# Install required packages
RUN apk update \
    && apk add --no-cache git \
        alpine-sdk \
    && go get -u github.com/cosmtrek/air \
    && go mod download

# Default settings at conatiner startup
# Hot reload settings
CMD ["air"]