# Base Image
FROM golang:1.14-alpine

# Specify Work Diectory
WORKDIR /go/src/app/

# Modules file allocation settings
COPY app/go.mod ./
COPY app/go.sum ./

RUN apk update \
    && apk add --no-cache git \
        alpine-sdk \
    && go get -u github.com/cosmtrek/air \
    && go mod download

CMD ["air", "main.go"]